import '../k29_screen/widgets/k6_item_widget.dart';import 'package:flutter/material.dart';import 'package:shop_smart/core/app_export.dart';import 'package:shop_smart/presentation/k15_page/k15_page.dart';import 'package:shop_smart/presentation/k16_page/k16_page.dart';import 'package:shop_smart/presentation/k22_page/k22_page.dart';import 'package:shop_smart/presentation/k24_page/k24_page.dart';import 'package:shop_smart/widgets/app_bar/appbar_image.dart';import 'package:shop_smart/widgets/app_bar/appbar_subtitle_1.dart';import 'package:shop_smart/widgets/app_bar/custom_app_bar.dart';import 'package:shop_smart/widgets/custom_bottom_bar.dart';import 'package:shop_smart/widgets/custom_elevated_button.dart';
// ignore_for_file: must_be_immutable
class K29Screen extends StatelessWidget {K29Screen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(56), centerTitle: true, title: AppbarSubtitle1(text: "سلة المشتريات"), actions: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowrightPrimary, margin: getMargin(all: 16))], styleType: Style.bgOutline_1), body: Container(width: double.maxFinite, padding: getPadding(top: 14, bottom: 14), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Expanded(child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(8));}, itemCount: 4, itemBuilder: (context, index) {return K6ItemWidget();})), Spacer(), Padding(padding: getPadding(left: 24, bottom: 22), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(text: "شراء الأن", buttonStyle: CustomButtonStyles.fillIndigo500TL16.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(150), getVerticalSize(80)))), buttonTextStyle: CustomTextStyles.titleLargePoppinsOnPrimary, onTap: () {onTaptf(context);}), Container(width: getHorizontalSize(180), margin: getMargin(left: 12), padding: getPadding(left: 15, top: 4, right: 15, bottom: 4), decoration: AppDecoration.fill6.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: getPadding(top: 20, bottom: 21), child: Text("342", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargePoppinsOnPrimary)), Padding(padding: getPadding(left: 24), child: SizedBox(height: getVerticalSize(70), child: VerticalDivider(width: getHorizontalSize(3), thickness: getVerticalSize(3), color: theme.colorScheme.onPrimary.withOpacity(1), indent: getHorizontalSize(10), endIndent: getHorizontalSize(10)))), Container(width: getHorizontalSize(59), margin: getMargin(left: 13, top: 7), child: Text("اجمالي المبلغ    ", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargePoppinsOnPrimary))]))]))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Ionhome: return AppRoutes.k24Page; case BottomBarEnum.Fasoliduserfriends: return AppRoutes.k15Page; case BottomBarEnum.Bag: return AppRoutes.k16Page; case BottomBarEnum.Jammessagesf: return AppRoutes.k22Page; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.k24Page: return K24Page(); case AppRoutes.k15Page: return K15Page(); case AppRoutes.k16Page: return K16Page(); case AppRoutes.k22Page: return K22Page(); default: return DefaultWidget();} } 
/// Navigates to the k30Screen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the `Navigator` widget
/// to push the named route for the k30Screen.
onTaptf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.k30Screen); } 
 }
