import 'package:flutter/material.dart';import 'package:shop_smart/core/app_export.dart';import 'package:shop_smart/widgets/custom_elevated_button.dart';import 'package:shop_smart/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class K7Screen extends StatelessWidget {K7Screen({Key? key}) : super(key: key);

TextEditingController emailController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: getPadding(left: 10, top: 41, right: 10, bottom: 41), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgUndrawcompletingrei7ap, height: getVerticalSize(307), width: getHorizontalSize(258)), CustomTextFormField(controller: emailController, margin: getMargin(left: 15, top: 63, right: 7), contentPadding: getPadding(top: 22, right: 18, bottom: 22), textStyle: CustomTextStyles.labelLargeInterOnPrimary, hintText: "البريد الالكتروني", hintStyle: CustomTextStyles.labelLargeInterOnPrimary, prefix: Container(margin: getMargin(left: 18, top: 19, right: 30, bottom: 19), child: CustomImageView(svgPath: ImageConstant.imgMail)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(62)), filled: true, fillColor: appTheme.indigo500), Container(margin: getMargin(left: 15, top: 8, right: 7), padding: getPadding(left: 20, top: 19, right: 20, bottom: 19), decoration: AppDecoration.outline.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(svgPath: ImageConstant.imgLockOnprimary, height: getSize(24), width: getSize(24)), Padding(padding: getPadding(top: 4, bottom: 2), child: Text("كلمة المرور", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.labelLargeInterOnPrimary))])), Container(margin: getMargin(left: 15, top: 8, right: 7), padding: getPadding(left: 18, top: 19, right: 18, bottom: 19), decoration: AppDecoration.outline.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgLockOnprimary, height: getSize(24), width: getSize(24)), Padding(padding: getPadding(top: 3, bottom: 3), child: Text("تأكيد كلمة المرور", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.labelLargeInterOnPrimary))])), CustomElevatedButton(text: "انهاء", margin: getMargin(left: 8, top: 46, bottom: 5), buttonStyle: CustomButtonStyles.outlineDeeppurple4007f.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(54)))), buttonTextStyle: CustomTextStyles.titleMediumOnPrimaryBold, onTap: () {onTaptf(context);})])))); } 
/// Navigates to the k8Screen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the `Navigator` widget
/// to push the named route for the k8Screen.
onTaptf(BuildContext context) { Navigator.pushNamed(context, AppRoutes.k8Screen); } 
 }
